# Generated by Django 4.1.4 on 2023-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
