# Generated by Django 4.1.3 on 2023-01-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0003_alter_startupmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('name', models.TextField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('about', models.TextField(max_length=200)),
                ('position', models.CharField(choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co-Founder'), ('CEO', 'Ceo')], default='CEO', max_length=10)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('startupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupmodel')),
            ],
        ),
    ]
