# Generated by Django 4.1.3 on 2023-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startupmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
