# Generated by Django 4.1.3 on 2023-01-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startupmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmodel',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='startup_images'),
        ),
    ]
